spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/dftm

jwt:
  secret: devSecretKey123456789012345678901234567890
  expiration: 86400000

logging:
  level:
    root: INFO
    com.dftm: DEBUG 